### ISSUE TITLE
Support configuration with multiple testSetXml and jmeterCsv

### ISSUE THREAD

**Issue by martymcflywa** [automatictester/lightning#109]
I'd like to be able to either provide a list of `jmeterCsv` items, or provide a path that contains multiple csv files in the maven plugin config, where all result files would be tested.

For example:

``` xml
<configuration>
  <mode>verify</mode>
  <testSetXml>src/test/resources/lightning.xml</testSetXml>
  <results>
    <jmeterCsv>target/jmeter/results/outputA.csv</jmeterCsv>
    <jmeterCsv>target/jmeter/results/outputB.csv</jmeterCsv>
  </results>
</configuration>
```

Or alternatively:

``` xml
<configuration>
  <mode>verify</mode>
  <testSetXml>src/test/resources/lightning.xml</testSetXml>
  <jmeterCsvPath>target/jmeter/results</jmeterCsvPath>
</configuration>
```

Is this a feature worthy for consideration? I'd be happy to contribute with a PR.

**Comment by automatictester** [comment]
Hi @martymcflywa, many thanks for opening this issue. I have never came across such a use case myself, which doesn't mean it wouldn't be valuable for other users. From what I can see, you'd like to have a single `testSetXml`, but multiple `jmeterCsv`. How would you see the analysis being executed here? Set of tests from `testSetXml` executed against each and every `jmeterCsv`, or set of tests from `testSetXml` executed against one set of JMeter input data (multiple `jmeterCsv` merged into one data set)?

**Comment by martymcflywa** [comment]
Thanks for the quick response. I was actually thinking about that just after i submitted the issue and thought I could achieve my goal with a single `testSetXml` executed against multiple `jmeterCsv`. But after looking at the integration tests in `jmeter-lightning-maven-plugin`, my use case would require defining multiple `testSetXml` files, mapped to specific `jmeterCsv` files.

Something like:

```
<configuration>
  <mode>verify</mode>
  <testMap>
    <testA>target/jmeter/results/resultsA.csv</testA>
    <testB>target/jmeter/results/resultsB.csv</testB>
  </results>
</configuration>
```

The keys of `testMap` point to files in assumed path `src/test/resources`.
The junit output files could be prefixed with the keys, ie. `testA-junit.xml`

**Comment by automatictester** [comment]
Currently you can define multiple executions:
```
                <executions>
                    <execution>
                        <id>lightning-1</id>
                        <goals>
                            <goal>lightning</goal>
                        </goals>
                        <configuration>
                            <mode>verify</mode>
                            <testSetXml>.../lightning-1.xml</testSetXml>
                            <jmeterCsv>.../example-1.csv</jmeterCsv>
                        </configuration>
                    </execution>
                    <execution>
                        <id>lightning-2</id>
                        <goals>
                            <goal>lightning</goal>
                        </goals>
                        <configuration>
                            <mode>verify</mode>
                            <testSetXml>.../lightning-2.xml</testSetXml>
                            <jmeterCsv>.../example-2.csv</jmeterCsv>
                        </configuration>
                    </execution>
                </executions>
```

The caveat is that subsequent execution overwrites previously generated `junit.xml`. So the only question to answer is how to make sure that JUnit reports are never overwritten. This could be done by adding new parameter `junitReportSuffix` to ConfigurationMojo. I'd see this param as follows:

- it should be optional
- when not set, no change from current behaviour
- when set to `abc`, JUnit report should be saved as `junit-abc.xml`

Implementing this functionality would require changes to lightning-core and jmeter-lightning-maven-plugin modules.
There is a few rough edges I can think of, but this should get us going. What do you think?

**Comment by martymcflywa** [comment]
Thanks for this great suggestion, it makes much more sense. What edge cases were you thinking of? I'll put together a PR for review shortly.

**Comment by automatictester** [comment]
Let's continue our discussion in PR 👍
