### ISSUE TITLE
Support wildcard for jmeterCsv filepaths

### ISSUE THREAD

**Issue by martymcflywa** [automatictester/lightning#111]
My jmeter csv result files are prefixed with a timestamp by `jmeter-maven-plugin`. I would like to be able to use wildcards (or ant style pattern matching) in the filepath when setting `jmeterCsv` in the lightning maven config.

Something like:

``` xml
<configuration>
  <mode>verify</mode>
  <testSetXml>src/test/resources/foo-testset.xml</testSetXml>
  <jmeterCsv>target/jmeter/results/*-foo-results.csv</jmeterCsv>
</configuration>
```

Would this feature be worth considering? If so, would appreciate your thoughts on how we could achieve this.

I'm thinking `jmeterCsv` would have to become a string and search the path for any matches. An exception is thrown if number of files found != 1.

Would be more than happy to contribute with a PR.

**Comment by automatictester** [comment]
I would solve this problem by not using timestamps in `jmeter-maven-plugin` (`<testResultsTimestamp>false</testResultsTimestamp>`). Would that solve your problem?
Having said that, I'm not against implementing functionality that you described. PR is welcome!

**Comment by martymcflywa** [comment]
Thanks for the suggestion! Much easier solution.
