### ISSUE TITLE
Reporting TeamCity Build Statistics

### ISSUE THREAD

**Issue by vizael** [automatictester/lightning#34]
It would be nice to report custom TeamCity Build Statistics, so that custom TC charts can be configured to track performance.
```
##teamcity[buildStatisticValue key='<valueTypeKey>' value='<value>']
```
https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildStatistics

**Comment by automatictester** [comment]
This could be interesting. Can you describe in more detail what specific information you'd like to be collected and give some examples?

Do you want to provide a PR for that?

**Comment by vizael** [comment]
Given we have output of one of Verify tests:
```
Test name:            API login - response time
Test type:            avgRespTimeTest
Test description:     Verify average response times
Transaction name:     API_login
Expected result:      Average response time <= 50
Actual result:        Average response time = 23.32
```

When we make additional stdout after all the tests, like this:
```
##teamcity[buildStatisticValue key='API login - response time' value='23.32']
```

Then we can go to the TC build => Statistics => Add new chart,
Give a new chart name "Login Response time",
Select "API login - response time" in dropdown,
Pick Data format as Float. https://confluence.jetbrains.com/display/TCD9/Statistic+Charts#StatisticCharts-BCStatistics

And we can enjoy chart that show how the average login time was changed over the time, given we have this build run daily.

**Comment by automatictester** [comment]
Thanks for detailed example. I think this feature could be useful.

Do you want to submit a PR for that? If not, I can spare some time, do a bit of research and implement that.

**Comment by vizael** [comment]
I'll do PR, but it will take some time, as I'm not a developer.

**Comment by automatictester** [comment]
Job title doesn't matter as long as you can craft quality code :) To make it easier for you to start, I can share how I can see this implemented:

* every non-abstract class in **uk.co.automatictester.lightning.tests** gets a new propertyto store the actual value (e.g. avg response time) with a public getter
* this value is set in **execute** method, together with **actualResult**
* **TeamCityReporter** needs to accommodate bunch of new things, which will be called from **CliTestRunner** inside **notifyCIServer**

**Comment by ggeda** [comment]
Also, try to do test- first when possible. Looks like you know what you want at the end if you can build that in terms of tests, then then the dev work could take care of itself.

Genene

**Comment by automatictester** [comment]
Hi @vizael, how is it going? Do you need any help?

**Comment by automatictester** [comment]
@vizael, do you plan to work on that in next few weeks' time?
