### ISSUE TITLE
[lightning] Support regular expressions in tests' transactionName node

### ISSUE THREAD

**Issue by automatictester** [automatictester/lightning#35]
Given config file contains

```
<avgRespTimeTest>
    <testName>Test #1</testName>
    <description>Verify average login times</description>
    <transactionName>.*page access</transactionName>
    <maxAvgRespTime>4000</maxAvgRespTime>
</avgRespTimeTest>
```

When JMeter transactions are parsed
Then only transaction with name equal to **.*page access** included.

---

Given config file contains

```
<avgRespTimeTest>
    <testName>Test #1</testName>
    <description>Verify average login times</description>
    <transactionName>.*page access</transactionName>
    </regexp>
    <maxAvgRespTime>4000</maxAvgRespTime>
</avgRespTimeTest>
```

When JMeter transactions are parsed
Then all transaction with name matching **.*page access** regular expression are included.

---

Above change is backwards-compatible. New behavior is applied only if **&lt;/regexp&gt;** is present.

Some implementation tips:
- add check for **regexp** element to all private methods in **LightningXMLFileReader**
- create helper method for the above in **LightningXMLProcessingHelpers**
- add **protected boolean regexp** to **LightningTest**, defaulting to **false**
- we will need a method in **JMeterTransactions** to cover both scenarios - exact match and regexp; currently **excludeLabelsOtherThan** handles only exact match

I assume this can be handled on **LightningTest** level and can be transparent for all non-abstract test classes in the same package.

**Comment by automatictester** [comment]
@szmc, do you plan to work on that in next few weeks' time?

**Comment by szmc** [comment]
Hi Irek,

Yes, I plan o work on this and finish till the end of month.

Cheers,
Szmc
